using System;
using meerkat.Enums;

namespace meerkat.Attributes;

/// <summary>
/// Specifies that a field or property is part of a compound index in MongoDB.
/// This attribute is used to define the index name and order for multi-field indexing.
/// </summary>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
public class CompoundIndexAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the name of the compound index.
    /// If not specified, the index name will be automatically generated by MongoDB.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the order of the index for this field or property.
    /// Defaults to <see cref="IndexOrder.Ascending"/>.
    /// </summary>
    public IndexOrder IndexOrder { get; set; } = IndexOrder.Ascending;
}
