using System;
using meerkat.Enums;

namespace meerkat.Attributes;

/// <summary>
/// Specifies that a field or property should be indexed as a geospatial index in MongoDB.
/// This attribute is used to define the index name and type for spatial queries.
/// </summary>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
public class GeospatialIndexAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the name of the geospatial index.
    /// If not specified, the index name will be automatically generated by MongoDB.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the type of the geospatial index.
    /// Available options: <see cref="GeospatialIndexType.TwoD"/> for planar geometry 
    /// and <see cref="GeospatialIndexType.TwoDSphere"/> for spherical geometry.
    /// Defaults to <see cref="GeospatialIndexType.TwoD"/>.
    /// </summary>
    public GeospatialIndexType IndexType { get; set; } = GeospatialIndexType.TwoD;
}
