using System;
using meerkat.Enums;

namespace meerkat.Attributes;

/// <summary>
/// Specifies that a field or property should have a single-field index in MongoDB.
/// This attribute is used to define the index name, order, and whether it should be sparse.
/// </summary>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
public class SingleFieldIndexAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the name of the index.
    /// If not specified, the index name will be automatically generated by MongoDB.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the order of the index.
    /// Defaults to <see cref="IndexOrder.Ascending"/>.
    /// </summary>
    public IndexOrder IndexOrder { get; set; } = IndexOrder.Ascending;

    /// <summary>
    /// Gets or sets a value indicating whether the index should be sparse.
    /// A sparse index only includes documents that contain the indexed field.
    /// Defaults to <c>false</c>.
    /// </summary>
    public bool Sparse { get; set; } = false;
}

