using System;

namespace meerkat.Attributes;

/// <summary>
/// Specifies that a field or property should have a unique index in MongoDB.
/// This attribute ensures that the indexed field contains only unique values across documents.
/// </summary>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
public class UniqueIndexAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the name of the unique index.
    /// If not specified, the index name will be automatically generated by MongoDB.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Determines how this index handles <c>null</c> values.
    /// If <c>true</c>, the index only includes documents that have the indexed field.
    /// If <c>false</c>, the index includes all documents, including those missing the indexed field.
    /// Defaults to <c>false</c>.
    /// </summary>
    public bool Sparse { get; set; } = false;
}

